unbind C-b
set-option -g prefix C-Space
# set-option -g terminal-overrides 'xterm*:smcup@:rmcup@'
bind-key C-Space send-prefix

bind j prev
bind k next

# Copy in iTerm2 by highlighting while holding CMD!!!
set -g mouse on

